name: initializable
description: A mixin to manage asynchronous operations during widget lifecycle events.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  async: ^2.12.0
